services:
  consul:
    image: hashicorp/consul:1.21.0
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      - "8600:8600/tcp"
    command: "agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -node=consul-server-1"
    volumes:
      - ./consul-data:/consul/data
      - ./consul-config:/consul/config
    environment:
      TZ: America/Los_Angeles
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
